### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by ghost** [morpho-os/framework#97] opened 2016-07-07 21:48 UTC
https://phpunit.de/manual/current/en/code-coverage-analysis.html

---
Related: #255 

See example: https://github.com/nikic/PHP-Parser/blob/d520bc9e1d6203c35a1ba20675b79a051c821a9e/.travis.yml#L13

**Comment by jackstr** [comment] 2021-07-13 04:08
Duplicate of #499.

**Closed by jackstr** 2021-07-13 04:08 UTC
Labels: normal-priority, qa
